POST http://127.0.0.1:8000/v1/banco HTTP/1.1
Content-Type: application/json


{
  "name": "kelvin",
  "password": "1234"
}

###
POST  http://127.0.0.1:8000/v1/transaction HTTP/1.1
Content-Type: application/json

{
    "typeTransaction":"person",
    "date_hour":"2025-06-25 12:55:00",
    "moto":100.4,
    "id_account":1,
    "id_device":1
}

  